Checkout, build tahoe from 'tahoe-lafs-1.12.1' tag
Recent changes to `tahoe run` (in the form of `tahoe daemonize`) cause
PyInstaller-frozen tahoe binaries to fail on run with the following:

Traceback (most recent call last):
      File "site-packages/twisted/internet/base.py", line 428, in fireEvent
      File "site-packages/twisted/internet/defer.py", line 321, in addCallback
      File "site-packages/twisted/internet/defer.py", line 310, in addCallbacks
      File "site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    --- <exception caught here> ---
      File "site-packages/twisted/internet/base.py", line 441, in _continueFiring
      File "site-packages/allmydata/scripts/tahoe_daemonize.py", line 128, in start
      File "site-packages/allmydata/scripts/tahoe_daemonize.py", line 117, in <lambda>
      File "site-packages/twisted/python/reflect.py", line 319, in namedAny
    exceptions.AttributeError: 'module' object has no attribute 'client'