Temporarily(?) pin ZKAPAuthorizer to 72a15f2...
Because the next change (5b1b9aa2dc0e37416866db2ea364793499315963)
breaks tahoe/PyInstaller packaging somehow, resuling in the following
tahoe error (observed when starting the tahoe daemon after configuring
it to connect to a ZKAPAuthorizer-enabled storage grid):

[_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Error
Traceback (most recent call last):
  File "twisted/internet/defer.py", line 322, in addCallback
  File "twisted/internet/defer.py", line 311, in addCallbacks
  File "twisted/internet/defer.py", line 654, in _runCallbacks
  File "nevow/appserver.py", line 464, in handleSegment
  --- <exception caught here> ---
  File "twisted/internet/defer.py", line 151, in maybeDeferred
  File "nevow/appserver.py", line 507, in locateChild
  File "twisted/web/resource.py", line 201, in getChildWithDefault
  File "allmydata/web/storage_plugins.py", line 30, in getChild
  File "allmydata/client.py", line 911, in get_client_storage_plugin_web_resources
  File "allmydata/storage_client.py", line 222, in get_client_storage_plugin_web_resources
  File "allmydata/storage_client.py", line 221, in <dictcomp>
exceptions.KeyError: u'privatestorageio-zkapauthz-v1'