Try expanding hiddenimports list for magic-folder
On Windows, Magic-Folder PyInstaller executables are failing to run:

Traceback (most recent call last):
  File "Lib\site-packages\magic_folder\__main__.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "magic_folder\cli.py", line 95, in <module>
  File "appdirs.py", line 196, in user_config_dir
  File "appdirs.py", line 81, in user_data_dir
  File "appdirs.py", line 480, in _get_win_folder_with_pywin32
ImportError: cannot import name 'shellcon' from 'win32com.shell' (D:\a\gridsync\gridsync\dist\Gridsync\win32com\shell\__init__.pyc)
[3216] Failed to execute script '__main__' due to unhandled exception!